import java.util.Scanner;
import java.util.Arrays;

public class extremeBonus{
    public static void main(String args[]){
        Scanner scan = new Scanner(System.in);
        Die d20 = new Die();
        d20.setFaces(20);
        Die d6 = new Die();
        d6.setFaces(6);
        
        String name;
        System.out.print("Hello, welcome to the lazy stat generator for Dungeons & Dragons.\nPlease tell me the name of your character: ");
        name = scan.nextLine();
        System.out.println("Welcome, "+name+".\n");
        
        //To create a character using a 20-sided die, you simply roll the dice and take it for your respective stat,
        System.out.println(name+"'s stats generated by d20 method: ");
        System.out.println("Strength: \t"+d20.roll()+"\nDexterity: \t"+d20.roll()+"\nConstitution: \t"+d20.roll()+"\nIntelligence: \t"+d20.roll()+"\nWisdom: \t"+d20.roll()+"\nCharisma: \t"+d20.roll());
        
        //To create a character using a 6-sided die, you roll 4 six-sided dice, sum all of them and subtract the one lowest dice.
        System.out.println("\n"+name+"'s stats generated by d6 method: ");
        System.out.println("Strength: \t"+d6.AdvancedRoll()+"\nDexterity: \t"+d6.AdvancedRoll()+"\nConstitution: \t"+d6.AdvancedRoll()+"\nIntelligence: \t"+d6.AdvancedRoll()+"\nWisdom: \t"+d6.AdvancedRoll()+"\nCharisma: \t"+d6.AdvancedRoll());
    }
}
